### PR TITLE
[FIX] DIDExchange handlers should do more signature checking #1226

### LINKED ISSUE #1226: [FIX] DIDExchange handlers should do more signature checking
I'm finding that currently, the `DIDExchange` requester and responder impls are not checking some cryptographic parts of the DIDExchange flow. Particularly:

1. ~when the inviter/responder _receives a request_, (`DidExchangeResponder::<ResponseSent>::receive_request`), then it should check that the wire-level sender of the request is from a key that matches a key of the DIDDoc inside the request. The spec says to do this:~
> ~After receiving the exchange request, the responder evaluates the provided DID and DID Doc according to the DID Method Spec.~
> ~The responder should check the information presented with the keys used in the wire-level message transmission to ensure they match.~

~I don't believe that ACAPy does this~

**EDIT: descoping this, as the community does not seem to find this case necessary: https://github.com/hyperledger/aries-rfcs/issues/717#issuecomment-1069768955**

2. when the invitee/requester _receives a response_ (`DidExchangeRequester::receive_response`), then it should check that DIDDoc or the DIDRotate attachment is signed JWS, and is signed with the original inviter key. The spec is clear on this:
> When the requester receives the response message, they will decrypt the authenticated envelope which confirms the source's authenticity. After decryption validation, the signature on the did_doc~attach or did_rotate~attach MUST be validated, if present. The key used in the signature MUST match the key used in the invitation. After attachment signature validation, they will update their wallet with the new information, and use that information in sending the complete message.

ACApy seems to do this

### PR DESCRIPTION
**Pull request by gmulhearn-anonyome**
branched off #1230 
diff: https://github.com/anonyome/aries-vcx/compare/gm/1228-did-exch-1_1...anonyome:aries-vcx:gm/1226-didexchange-signature-checks

fixes part 2 of #1226.

adds JWS signature verification when receiving a response. The new approach mostly matches ACApy's implementation found here: https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/didexchange/v1_0/manager.py#L942.

It is a relatively aggressive approach where it will fail if neither DIDDoc attachments nor DIDRotate attachment have signatures.

### CODE REVIEW

**Comment by gmulhearn-anonyome** [comment]
TODO - verify still working in Acapy aath

**Comment by gmulhearn-anonyome** [comment]
@JamesKEbert this is ready for review after #1230 is merged

**Comment by gmulhearn-anonyome** [comment]
alright this should be good to go

File: aries/aries_vcx/src/protocols/did_exchange/state_machine/helpers.rs [hunk 1]
```diff
@@ -180,51 +180,111 @@ pub(crate) fn assemble_did_rotate_attachment(did: &Did) -> Attachment {
...
+                "Attachment JWS signature was not correctly base64Url encoded.",
+            )
+        })?;
+
+    let res = wallet
+        .verify(expected_signer, &sign_input, &signature)
+        .await?;
+
+    Ok(res)
 }
```
Comment (JamesKEbert) [inline aries/aries_vcx/src/protocols/did_exchange/state_machine/helpers.rs:288]: Would it be appropriate to have a test case for this? Or is that adding a test for test's sake?

File: aries/aries_vcx/src/protocols/did_exchange/mod.rs [hunk 2]
```diff
@@ -103,11 +106,25 @@ pub async fn resolve_enc_key_from_invitation(
                 "resolve_enc_key_from_invitation >> Resolved did document {}",
                 output.did_document
             );
-            let key = resolve_first_key_agreement(&output.did_document)?;
```
Comment (JamesKEbert) [inline aries/aries_vcx/src/protocols/did_exchange/mod.rs:106]: Do you think `resolve_first_key_agreement()` is still a valid/useful function with this change? Just curious, no strong opinion from my side

File: aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs [hunk 3]
```diff
@@ -134,3 +130,96 @@ impl DidExchangeRequester<RequestSent> {
...
+            ..
+        } = resolver_registry.resolve(did, &Default::default()).await?;
+        return Ok(did_doc);
+    }
+
+    // default to error
+    Err(AriesVcxError::from_msg(
+        AriesVcxErrorKind::InvalidInput,
+        "DIDExchange response could not be verified. No DIDDoc nor DIDRotate was attached.",
+    ))
```
Comment (JamesKEbert) [inline aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs:224]: Do we have a strategy in Aries VCX as how to abort a protocol and send a problem report? As I would think this would be an appropriate time to create a problem report.

Comment (JamesKEbert) [reply aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs:224]: I recognize that's somewhat outside the scope of this PR, but it came to mind while reviewing

File: aries/aries_vcx/src/protocols/did_exchange/state_machine/helpers.rs (hunk 1 above)
Comment (JamesKEbert) [reply aries/aries_vcx/src/protocols/did_exchange/state_machine/helpers.rs:288]: I suppose this might be covered under the `did_exchange_test_with_invalid_rotation_signature` test case. :thinking:

**Review by JamesKEbert — DISMISSED** [review]
Looks good to me--good additions! I left some minor thoughts, but that may not need to hold up merging

File: aries/aries_vcx/src/protocols/did_exchange/mod.rs (hunk 2 above)
Comment (gmulhearn) [reply aries/aries_vcx/src/protocols/did_exchange/mod.rs:106]: hmm yea it's a tough one. Ideally, DIDDocs that we resolve will have:
* a service with a recipient key

and then we just just use that recipient key as the peer's "encryption key".

However it is possible that some DIDs may not be perfect, and they will have a service, but no recipient keys, in which case, i think it's a decent backup solution to use the first key agreement key (`resolve_first_key_agreement`).

The above is the `resolve_enc_key_from_did_doc` after these changes. I don't think it's perfect, but i think this might be a situation where we need to handle random interop edge cases as they reveal themselves over time... atleast we know it interops with ourselves and with ACApy

File: aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs (hunk 3 above)
Comment (gmulhearn) [reply aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs:224]: Hmmm, so this protocol state machine is a little different to some of the other state machines in aries-vcx (this one is the "most modern"), but the handler has a `.fail` method and `.receive_problem_report` method which creates and processes problem report messages: https://github.com/hyperledger/aries-vcx/blob/main/aries/aries_vcx/src/protocols/did_exchange/state_machine/mod.rs#L37

I think the thinking was that, you get returned a TransitionError, you should process the error and decide if it's a fatal error or not; and subsequently decide if you want to create a problem report with `.fail`, or just try again

File: aries/aries_vcx/src/protocols/did_exchange/state_machine/helpers.rs (hunk 1 above)
Comment (gmulhearn) [reply aries/aries_vcx/src/protocols/did_exchange/state_machine/helpers.rs:288]: Yeah the did_exchange_tests should cover a lot of this code in the happy and negative path. But i just added some better direct tests, testing self-fulfilling-ly and also testing against an acapy test vector i recorded

File: aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs (hunk 3 above)
Comment (gmulhearn) [reply aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs:224]: it isn't being tested or demonstrated anywhere though.. so i think in general it's been a bit neglected

Comment (JamesKEbert) [reply aries/aries_vcx/src/protocols/did_exchange/state_machine/requester/request_sent/mod.rs:224]: Got it. I'd say that perhaps it's something we should look at at some point, but would be outside the scope of this PR.

**Review by JamesKEbert — APPROVED** [review]
LGTM
